version: "3.3"
services:
  jenkins:
    image: marzepka/mrchecker-jenkins:v1.1.2
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: dockerfile
  reverse-proxy:
    #build: 'reverse-proxy/'
    restart: always
    #container_name: 'mts_reverse_proxy'
    image: docker.pkg.github.com/devonfw/my-thai-star/reverse-proxy   #docker pull docker.pkg.github.com/devonfw/my-thai-star/reverse-proxy:latest
    networks:
      - my-thai-star
    ports:
      - '8081:80'
  angular:
    #build: 'angular/'
    restart: always
    #container_name: 'mts_angular'
    image: docker.pkg.github.com/devonfw/my-thai-star/angular:latest #docker pull docker.pkg.github.com/devonfw/my-thai-star/angular:latest
    networks:
      - my-thai-star
  java:
    #build: 'java/'
    restart: always
    #container_name: 'mts_java'
    image: docker.pkg.github.com/devonfw/my-thai-star/java:latest #docker pull docker.pkg.github.com/devonfw/my-thai-star/java:latest
    networks:
      - my-thai-star
networks:
  my-thai-star:
    driver: bridge
