env.module = "${JOB_NAME}".split('/')[0]
env.workspace = "mrchecker-framework-modules"
pipeline{
	agent {docker {image 'marzepka/mrchecker:v1.1.2'}}
	stages{
		stage('Build'){
			steps{
				echo "Building module ${env.module} and it's dependency"
				sh """
				cd ${env.workspace}
				mvn clean compile package -DskipTests=true --projects ${env.module} --also-make
				"""
			}
		}
		stage('Test'){
			steps{
				echo "Testing ${env.module}"
				sh """
				cd ${env.workspace}/${env.module}
				mvn test
				"""
			}
		}
	}
	post{
		always{
			archiveArtifacts artifacts: "${env.workspace}/target/*.jar", fingerprint: true
			junit '**/surefire-reports/*.xml'
		}
	}
}
