env.module = "${JOB_NAME}".split('/')[0]
env.workspace = "mrchecker-framework-modules/${env.module}"
pipeline{
	agent {docker {image 'marzepka/mrchecker:v1.1.2'}}
	stages{
		stage('Build'){
			steps{

				sh """
				cd ${env.workspace}
				mvn clean compile package -DskipTests=true
				"""
			}
		}
		stage('Test'){
			steps{
				sh """
				cd ${env.workspace}
				mvn test
				"""
			}
		}
	}
	// post{
	// 	always{
	//		archiveArtifacts artifacts: 'build/libs/**/*.jar', fingerprint: true
	// 		junit 'build/reports/**/*.xml'
	// 	}
	// }
}
