FROM maven:3.6.3-jdk-8


# Jenkins runs with user `jenkins`, uid = 1000
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
RUN addgroup --gid ${gid} ${group} && adduser --disabled-password  --uid ${uid} --gid ${gid} ${user}

ARG workspace=/workspace
RUN mkdir -p -m 777 ${workspace}
WORKDIR ${workspace}
USER root
#for mrchecker-selenium-module
RUN apt-get update \
    && apt-get install -y xvfb libxi6 libgconf-2-4

#for mrchecker-mobile-module

USER ${user}
