FROM ubuntu:focal
RUN apt update && apt install -y \
	git\
	curl\
	unzip\
	zip
RUN curl -s "https://get.sdkman.io" | bash && chmod a+x "$HOME/.sdkman/bin/sdkman-init.sh"
RUN ["/bin/bash","-c", "source \"$HOME/.sdkman/bin/sdkman-init.sh\" && sdk install java 8.0.252-open && sdk install maven 3.6.3"]