FROM maven:3.6.3-jdk-8

# Jenkins runs with user `jenkins`, uid = 1000
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
RUN addgroup --gid ${gid} ${group} && adduser --disabled-password  --uid ${uid} --gid ${gid} ${user}

ARG workspace=/workspace
RUN mkdir -p -m 777 ${workspace}
WORKDIR ${workspace}
USER ${user}
